---
- name: "Apache installation using Docker on CentOS 7"
  hosts: prod
  become: true
  vars:
    ansible_sudo_pass: vagrant
    ansible_python_interpreter: /usr/bin/python2
  vars_files:
    - files/secrets/credentials.yml
  pre_tasks:
    - name: Install EPEL repo (for CentOS)
      package: name={{ item }} state=present
      when: ansible_distribution == "CentOS"
      loop:
        - epel-release
        - wget
        - git
    - name: Install Python 3 and pip3
      package:
        name:
          - python3
          - python3-pip
        state: present
    - name: Install Docker module for Python
      pip:
        name: docker
        executable: pip3
  tasks:
    - name: Copy website file templates
      templates:
        src: index.html.j2
        dest: /home/vagrant/index.html
    - name: Create Apache container using Docker
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes: 
         - /home/vagrant/index.html:/usr/local/apache2/htdocs/index.html
